name: Build simples (sem jlink)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven
        working-directory: src/SistemaDeTarefasFX
        run: mvn clean package

      - name: Copiar dependências
        working-directory: src/SistemaDeTarefasFX
        run: mvn dependency:copy-dependencies

      - name: Criar .exe (sem jlink)
        shell: cmd
        run: |
          jpackage ^
          --input src\SistemaDeTarefasFX\target ^
          --name SistemaDeTarefas ^
          --main-jar SistemaDeTarefasFX-1.0-SNAPSHOT.jar ^
          --main-class sistema.de.tarefas.Launcher ^
          --type exe ^
          --dest output

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: output\*
