name: Build com jlink (Executável real)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven
        run: mvn clean package

        working-directory: src/SistemaDeTarefasFX

      - name: Criar runtime com jlink
        run: |
          jlink ^
            --module-path "%JAVA_HOME%\jmods;src\SistemaDeTarefasFX\target\dependency" ^
            --add-modules java.base,javafx.controls,javafx.fxml ^
            --output runtime

      - name: Criar .exe com jpackage
        run: |
          jpackage ^
            --input src\SistemaDeTarefasFX\target ^
            --name SistemaDeTarefas ^
            --main-jar SistemaDeTarefasFX-1.0-SNAPSHOT.jar ^
            --main-class sistema.de.tarefas.Launcher ^
            --runtime-image runtime ^
            --type exe ^
            --dest output

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: output\*
